"""Version identity/replay checks; model semantic quality needs provider evidence."""

import json
from pathlib import Path

import pytest

from companion_daemon.world_v2 import visible_source_closure_protocol as protocol
from companion_daemon.world_v2.visible_source_review_receipt import (
    VisibleSourceReviewReceipt, _hash, _json,
)


@pytest.mark.parametrize("version,expected", [
    ("3", "46116244ee06346ff8496e446f6b79f44910e3285eb9221b19e2fb210d3f76b5"),
    ("4", "4b134af6c28ba72e64931e90e6c19101b48556cefa0d1850411521044b694c7c"),
])
def test_pre_v5_receipts_keep_exact_preparation_and_cold_verification(version, expected):
    # Frozen using f7271f51 before implementing v5, not regenerated by this test.
    path = Path(__file__).parent / f"fixtures/visible_source_review_receipt_v{version}.json"
    raw = path.read_text().removesuffix("\n")
    assert _hash(raw) == expected
    receipt = VisibleSourceReviewReceipt.model_validate_json(raw, strict=True)
    assert _json(receipt.model_dump(mode="json")) == raw


def test_v5_cannot_be_substituted_for_v4_in_provider_or_receipt_identity():
    old = protocol.visible_source_verdict_provider_request_contract(version="4")
    new = protocol.visible_source_verdict_provider_request_contract(version="5")
    assert new["contract"] == "visible-beat-source-verdict.5"
    assert new["tool_choice"]["function"]["name"] == "visible_beat_source_verdict_v5"
    assert new["schema_digest"] != old["schema_digest"]
    raw = json.dumps({
        "contract": "visible-beat-source-verdict.4",
        "decisions": [{"beat_index": 0, "verdict": "source_free",
                       "semantic_role": "private_state", "subject_role": "companion"}],
        "rejections": [],
    })
    with pytest.raises(protocol.VisibleSourceClosureWireFailure, match="branch transport"):
        protocol.parse_visible_source_verdict(
            raw, version="5", visible_beats=("还有点困",), source_ref_kinds=(),
        )
    fixture = Path(__file__).parent / "fixtures/visible_source_review_receipt_v4.json"
    forged = json.loads(fixture.read_text())
    forged["contract"] = "visible-source-review-receipt.5"
    with pytest.raises(ValueError):
        VisibleSourceReviewReceipt.model_validate_json(json.dumps(forged), strict=True)
