"""Version identities shared by composition, transport and immutable receipts.

No provider or domain imports: entry points can agree on support without
importing the reviewer implementation or maintaining divergent allowlists.
"""
PROTOCOL = "visible-independent-review.1"
RESELECTING_PROTOCOL = "visible-independent-review.2"
SHARED_STRING_PROTOCOL = "visible-independent-review.3"
SUBJECTIVE_HISTORY_PROTOCOL = "visible-independent-review.4"
CONTENT_FIELD_PROTOCOL = "visible-independent-review.5"
PRESUPPOSITION_PROTOCOL = "visible-independent-review.6"
PREHISTORY_PROTOCOL = "visible-independent-review.7"
CONDITION_WIRE_PROTOCOL = "visible-independent-review.8"
CONTEXTUAL_PROTOCOL = "visible-independent-review.9"
SCOPED_COVERAGE_PROTOCOL = "visible-independent-review.10"
FACT_VALUE_PROTOCOL = "visible-independent-review.11"
PRIVATE_COGNITION_PROTOCOL = "visible-independent-review.12"
RECORD_DEPENDENCY_PROTOCOL = "visible-independent-review.13"
LIFECYCLE_FIELD_PROTOCOL = "visible-independent-review.14"
SOURCE_USE_DISPLAY_PROTOCOL = "visible-independent-review.15"
LIFECYCLE_FIELD_PROTOCOLS = frozenset((LIFECYCLE_FIELD_PROTOCOL, SOURCE_USE_DISPLAY_PROTOCOL))
RECORD_DEPENDENCY_PROTOCOLS = frozenset((RECORD_DEPENDENCY_PROTOCOL, *LIFECYCLE_FIELD_PROTOCOLS))
PRIVATE_COGNITION_PROTOCOLS = frozenset((PRIVATE_COGNITION_PROTOCOL, *RECORD_DEPENDENCY_PROTOCOLS))
FACT_VALUE_PROTOCOLS = frozenset((FACT_VALUE_PROTOCOL, *PRIVATE_COGNITION_PROTOCOLS))
SCOPED_COVERAGE_PROTOCOLS = frozenset((SCOPED_COVERAGE_PROTOCOL, *FACT_VALUE_PROTOCOLS))
CONTEXTUAL_PROTOCOLS = frozenset((CONTEXTUAL_PROTOCOL, *SCOPED_COVERAGE_PROTOCOLS))
CONDITION_WIRE_PROTOCOLS = frozenset((CONDITION_WIRE_PROTOCOL, *CONTEXTUAL_PROTOCOLS))
PREHISTORY_PROTOCOLS = frozenset((PREHISTORY_PROTOCOL, *CONDITION_WIRE_PROTOCOLS))
PRESUPPOSITION_PROTOCOLS = frozenset((PRESUPPOSITION_PROTOCOL, *PREHISTORY_PROTOCOLS))
CONTENT_FIELD_PROTOCOLS = frozenset((CONTENT_FIELD_PROTOCOL, *PRESUPPOSITION_PROTOCOLS))
SUBJECTIVE_HISTORY_PROTOCOLS = frozenset((SUBJECTIVE_HISTORY_PROTOCOL, *CONTENT_FIELD_PROTOCOLS))
SHARED_STRING_PROTOCOLS = frozenset((SHARED_STRING_PROTOCOL, *SUBJECTIVE_HISTORY_PROTOCOLS))
RESELECTING_PROTOCOLS = frozenset((RESELECTING_PROTOCOL, *SHARED_STRING_PROTOCOLS))
REVIEW_PROTOCOLS = {"9": PROTOCOL, "10": RESELECTING_PROTOCOL, "11": SHARED_STRING_PROTOCOL, "12": SUBJECTIVE_HISTORY_PROTOCOL, "13": CONTENT_FIELD_PROTOCOL, "14": PRESUPPOSITION_PROTOCOL, "15": PREHISTORY_PROTOCOL, "16": CONDITION_WIRE_PROTOCOL, "17": CONTEXTUAL_PROTOCOL, "18": SCOPED_COVERAGE_PROTOCOL, "19": FACT_VALUE_PROTOCOL, "20": PRIVATE_COGNITION_PROTOCOL, "21": RECORD_DEPENDENCY_PROTOCOL, "22": LIFECYCLE_FIELD_PROTOCOL, "23": SOURCE_USE_DISPLAY_PROTOCOL}
RECEIPT_PROTOCOLS = {p: f"visible-source-review-receipt.{v}" for v, p in REVIEW_PROTOCOLS.items()}
# The current single-review path has its own compiler. Historical independent
# protocols keep their exact two-reader request and receipt contracts.
GROUNDED_REVIEW_VERSION = "24"
GROUNDED_REVIEW_PROTOCOL = "visible-grounded-review.1"
PINNED_REVIEW_PROTOCOLS = {**REVIEW_PROTOCOLS, GROUNDED_REVIEW_VERSION: GROUNDED_REVIEW_PROTOCOL}
SUPPORTED_REVIEW_VERSIONS = ("1", "2", "3", "4", "5", "6", "7", "8", *PINNED_REVIEW_PROTOCOLS)


def visible_review_protocol(version):
    return PINNED_REVIEW_PROTOCOLS.get(version)
